### ISSUE TITLE
npm install for 2.0.0 doesn't pull down ./dist

### ISSUE THREAD

**Issue by andrew-white** [rannn505/node-powershell#11]
Running `npm install node-powershell` I get the following:

```
$ ls -1
LICENSE
README.md
example
node_modules
package.json
```
If I manually create `dist` and drop in the files from the git repo, everything works as expected.

**Comment by rannn505** [comment]
Hey @andrew-white 
My mistake, I forgot to update files section in package.json.
Anyway, I fixed it ... Thank you for your attention and caring :+1:  :100:
