### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by vijhhh2** [rannn505/node-powershell#110]
Hi, I want to know weather this project is still maintaining by @rannn505. Because i have seen the last commit was 12 years ago

**Comment by Younanator** [comment]
If you look at the comments you can see he's commenting and updating people so yes.

**Comment by rannn505** [comment]
![image](https://user-images.githubusercontent.com/11806915/74192627-9180de00-4c5e-11ea-8dfe-22abcdb4bfcd.png)
And there are many more to come :) ... I will release a new version shortly :)
