### ISSUE TITLE
Documentation: .addArgument() / .addParameter() / .addParameters() calls in sample commands are incorrect

### ISSUE THREAD

**Issue by mklement0** [rannn505/node-powershell#115]
For instance, https://rannn505.gitbook.io/node-powershell/shell/addparameter shows:

```js
// 'Write-Host node-powershell -foregroundcolor red -nonewline'
ps.addCommand('Write-Host node-powershell')
  .then(() => ps.addParameter({foregroundcolor: 'red'}))
  .then(() => ps.addParameter({nonewline: null})) //switch;
```

The command doesn't actually work unless you remove the `.then() => ` part.

That is, the method calls must be independent statements for argument / parameter passing to work.

This has been reported before, but the issue closed by the reporter him/herself without resolution: #109

**Comment by rannn505** [comment]
@mklement0 , please wait for the new version.. its pretty much what you asked for!
