### ISSUE TITLE
Does Node-PowerShell on Mac require that PowerShell is already installed on Mac?

### ISSUE THREAD

**Issue by TCourtneyOwen** [rannn505/node-powershell#124]
I assume Node-PowerShell on Mac requires that PowerShell be installed on Mac, but just want to clarify before I be investigating using this package. Can you please clarify? 

Thanks,

Courtney

**Comment by rannn505** [comment]
@TCourtneyOwen Yap as for now it is required.
The new version will have a postinstall script that will download the binary into node_modules -> .bin dir so you dont have to install it globally 👍
