### ISSUE TITLE
Unable to send array of strings

### ISSUE THREAD

**Issue by shareiff** [rannn505/node-powershell#15]
I am unable to send an array of Strings. When I send a JS array it reads it as one long string in the powershell script (i.e. it only loops through once in my powershell foreach loop) . I've also tried sending it formatted as a powershell array @()

JS
```
let users = ["account1", "account2"]
let params = [{name: 'Accounts', value: users}]
ps.addCommand(filePath + 'Enable-ADUser.ps1', params)
return ps.invoke()
```
Powershell
```
Param (
   [Parameter(Mandatory = $true)]
   [String[]] $Accounts
)
```

Not sure where I'm going wrong. Are we able to send an array to powershell?

Thank you!

**Comment by rannn505** [comment]
Hey @shareiff ,
Thank you for helping me find this bug. 
Anyway I will make some tests, fix it, and come out with a new version, soon. 🥇

**Comment by shareiff** [comment]
Thanks! no rush, I figure I can just wrap the ps.addCommand() in a for-loop

**Comment by rannn505** [comment]
Hey @shareiff 
Please check out the new features entered in the last commit.
Thx. 👍
