### ISSUE TITLE
TypeError: shell is not a constructor

### ISSUE THREAD

**Issue by forensicsguy20012004** [rannn505/node-powershell#16]
I am running the following: var ps = new shell({executionPolicy: 'Bypass', debugMsg: true, noProfile: true});
and received the following error: [TypeError: shell is not a constructor]

any thoughts

**Comment by rannn505** [comment]
Hey @forensicsguy20012004 ,
I suggest you try to re-install the module.
Besides, did you remember to add this line first?
``` javascript
const shell = require('node-powershell');
```
Let me know if you managed to solved this, or you need further help.
GL and THx :+1:

**Comment by forensicsguy20012004** [comment]
Hello...thanks for replying back so quickly :) 

So I ran the following code....

var shell = require('node-powershell');
var ps = new shell({executionPolicy: 'Bypass', debugMsg: true, noProfile: true});
ps.addCommand('echo "node-powershell rocks"')
    .then(function(){
        return ps.invoke();
    })
    .then(function(output){
        console.log(output);
        ps.dispose();
    })
    .catch(function(err){
        console.log(err);
        ps.dispose();
    });

I installed via NPM doing: npm install node-powershell --save

I have not been able to get this working...yet...I am hoping I will or I will find something.

I am running v6.9.1 on a Windows 7 box.

**Comment by forensicsguy20012004** [comment]
Info: Start process (6:42:23 PM)
Error: 
var ps = new shell({executionPolicy: 'Bypass', debugMsg: true, noProfile: true});
         ^

TypeError: shell is not a constructor
    at Object.<anonymous> (c:\NodeProjects\Spartan\node_302d72ae491fb.tmp:3:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

Info: End process (6:42:24 PM)

![image](https://cloud.githubusercontent.com/assets/12624999/22446731/261d0922-e71c-11e6-9724-273cfe56e869.png)

I have run this a couple different ways...so I am not getting an error about the module not being loaded or available. I will try anything.

**Comment by rannn505** [comment]
Hey @forensicsguy20012004 ,
After reading [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_a_constructor)
The two reasonable things that could happened is that either the module is not loaded correctly from some reason... or that you use shell variable elsewhere in your code ... I would suggest that once again, you will open an empty folder and try to run the example... Anyway I will try to publish a new version at the beginning of next week maybe .. maybe this would solve it.
Have a nice day and keep updating!

**Comment by forensicsguy20012004** [comment]
Sorry for responding back so late...I will give that a try and look forward to a new push of your module. Keep up the good work :)

**Comment by forensicsguy20012004** [comment]
So, I pulled down your newest version via NPM:  "node-powershell": "3.0.1"...still getting the same error. My guess is, it has got to be something that I am doing. I am pretty adept as Node but for some reason this escapes me.

`var ps = new shell({executionPolicy: 'Bypass', debugMsg: true, noProfile: true});
         ^
TypeError: shell is not a constructor
    at Object.<anonymous> (C:\nodeprojects\spartan\NodePowershell.js:3:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
`

**Comment by rannn505** [comment]
Hey @forensicsguy20012004 
Please check out the new features entered in the last commit. and try again.
Thx. 👍

**Comment by Suppenterrine** [comment]
Hello @rannn505,

I have the same problem as @forensicsguy20012004.
I tried re-installing the module but that didn't fixed the issue for me.

This is the code I was trying to run:
```js
const Shell = require('node-powershell');

const ps = new Shell({
  executionPolicy: 'Bypass',
  noProfile: true
});

ps.addCommand('echo node-powershell');
ps.invoke()
.then(output => {
  console.log(output);
})
.catch(err => {
  console.log(err);
});
```

I copied this code from StackOverflow and wanted to test it, but I don't know how to workaround this error.
Is it working for you?
