### ISSUE TITLE
Unable to send [switch] options.

### ISSUE THREAD

**Issue by PmoriartyPhoenix** [rannn505/node-powershell#17]
I was trying to send a switch options to node-powershell

var shell = require('node-powershell');

var ps = new shell

ps.addCommand('write-host "powerShell"', [{name: 'nonewline'}]).then( ps.invoke())

result from console.log is  write-host "powerShell" -nonewline "undefined" rather than write-host "powerShell" -nonewline

**Comment by rannn505** [comment]
Hey @PmoriartyPhoenix 
Please check out the new features entered in the last commit.
Thx. 👍

**Comment by PmoriartyPhoenix** [comment]
Thanks. Any plans for Boolean?  Convert true to $true and false to $false?

**Comment by rannn505** [comment]
Its also in the new version. it now support most of JS to PS data types (Date, Boolean, Array, switch, numbers and more ....)
