### ISSUE TITLE
Intermittently the data from the power shell instance is blank

### ISSUE THREAD

**Issue by PmoriartyPhoenix** [rannn505/node-powershell#20]
Intermittently but frequently, I get back an empty string from node-power shell in the then of the promise when the console shows it received data.  Rerunning of the command on a new shell instance returns the data.  

This is most previlant when I pool and reuse powershell instances, but I can also see this behavior on freshly spawned instances of the shell object. 

Any ideas how to get around this and get a reliable return?  

Test powershell command is ls | convert-to-json -compress.  (Large file set)

Also have bluebird overwriting my Promise object.  Node 6.9.1 windows 10

**Comment by mattflix** [comment]
Note that issue #26 may be related.
