### ISSUE TITLE
Escaping string input

### ISSUE THREAD

**Issue by Xainey** [rannn505/node-powershell#21]
Correct me if I'm wrong on this. I've been passing JSON strings into PowerShell scripts then using `ConvertFrom-Json` to convert it to a hashtable. I noticed a few issues on the first few attempts. The workaround is simple enough, but perhaps JSON strings should be passable as params without needing to manually escape or wrap the input strings.

Using a parm block like `{ name: JSON.stringify({ name: "Mike" }) }`
results in a call like `test-string.ps1 -name {"name":"Mike"}` which breaks on the powershell call.
To fix this I have to serialize my JSON then wrap it in single quotes or double quotes if it is escaped.

Here is a contrived example.

test-string.ps1
```
param (
    [Parameter(Mandatory = $true)]
    [string] $Name
)
$Name
```

test-script.js
```
    let ps = new shell({
        executionPolicy: 'Bypass',
        noProfile: true
    });

    let scriptPath = require("path").resolve(__dirname, './test-string.ps1')
    ps.addCommand(scriptPath, [
        //  { name: "Hello World" } // Good
        //  { name: "Hello 'again' World" } // Good
        //  { name: 'Hello World' } // Good
        //  { name: 'Hello "again" World' } // Bad
        //  { name: JSON.stringify({name: 'Mike'}) } // Bad
        //  { name: "'" + JSON.stringify({name: 'Mike'}) + "'" } // Good
    ])
    ps.invoke()
    .then(output => {
        console.log(output)
    })
    .catch(err => {
        console.log(err);
        ps.dispose();
    });
```

**Comment by BenjaminMichael** [comment]
I use backticks and string literals for these

{ name: `Hello ""again"" World` } //good
{ name: `'${JSON.stringify({name: 'Mike'})}'` } // Good
