### ISSUE TITLE
Better Error passing to JS

### ISSUE THREAD

**Issue by Xainey** [rannn505/node-powershell#22]
Given a simple `throw "whoops"` in PowerShell the message 

```
whoops
At line:2 char:5
+     throw "whoops"
+     ~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (whoops:String) [], RuntimeException
    + FullyQualifiedErrorId : whoops
```

gets passed along to the JS.

It would be much easier to handle custom exceptions and display messages in the JS/frontend side if the exception object was serialized and passed from PS->JS. On the JS side, I may want to use the message, error id, line number, script name, etc.

```
try {
    throw "whoops"
} catch {
    $_ | ConvertTo-Json
}
```

With the above example, you mainly rely on the `$_.Exception.Message` or `$_.Message`

Some projects, Pester for instance, use a custom function to make their own Error ID.
Take the following:

```
function New-ErrorRecord ([string] $ErrorID, [string] $Message, [HashTable] $Custom) {
    $errorCategory = [Management.Automation.ErrorCategory]::InvalidResult
    $exception = New-Object Exception $Message
    $errorRecord = New-Object Management.Automation.ErrorRecord $exception, $ErrorID, $errorCategory, $Custom

    $errorRecord
}

try {
    throw New-ErrorRecord -ErrorID "Crap.Its.Friday" -Message "You probably shouldn't do this today."
}
catch {
    $_ | ConvertTo-Json
}
```

Now you can use:

```
$_.FullyQualifiedErrorId
$_.Message
```

to get the type and message.

**Comment by rannn505** [comment]
Hey @Xainey,

The output of the error depends on the script writer.
I totally agree with that using your method, it will be much easier to work with error objects in the JS side.
I would suggest you publish a guide on how to do it right in combination with Node-PowerShell, 
And maybe even send me a good example to publish in the tips section in the official documentation.

Thx 💯
