### ISSUE TITLE
Node commands in Powershell

### ISSUE THREAD

**Issue by dotnetspec** [rannn505/node-powershell#24]
Hi,
I have downloaded and installed via:
npm i -S node-powershell
yarn add node-powershell

I run the 'Quick Start' script from within a PS script and get:

At C:\Users\jonathon2\Ethereum Projects\helloWorldVoting\NPSdemo.ps1:10 char:11
+ ps.invoke()
+           ~
An expression was expected after '('.
At C:\Users\jonathon2\Ethereum Projects\helloWorldVoting\NPSdemo.ps1:16 char:14
+   ps.dispose();
+              ~
An expression was expected after '('.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ExpectedExpression

I want to script a series of node commands from within PowerShell.

I'm probably missing something basic. What am I doing wrong?
Thx.

**Comment by BenjaminMichael** [comment]
node-powershell is for invoking commands in Powershell from Node.  It sounds like you want to do the opposite, to invoke Node API calls from Powershell.  I do not think you can do that.  You can invoke JScript script blocks but you dont get the awesome power of node and npm.
