### ISSUE TITLE
addCommand("ls c:") followed by invoke() always emits nothing (blank string)

### ISSUE THREAD

**Issue by mattflix** [rannn505/node-powershell#25]
Software used:
* node-powershell 3.1.1
* node 7.9.0
* PowerShell 5.1.14393.1198
* Windows 10 (1607)

I have noticed that ```addCommand("ls c:")``` followed by ```invoke()``` always emits nothing (just a blank string).

While I can get very simple "toy" commands (e.g., "echo hello") to work, even the following basic "non-toy" (i.e., one might actually want to do this) example always returns nothing:

```javascript
const shell = new Shell({ debugMsg: false });
await shell.addCommand("ls c:");
const output = await shell.invoke();
console.log(output); // "" (blank)
```

Yet, when the same command (```ls c:```) is run manually at the PowerShell prompt,  it obviously emits the top-level of my C: drive (several files and folders).

Then, I tried some experiments.

**Experiment 1**

```javascript
const shell = new Shell({ debugMsg: false });
await shell.addCommand("echo HEAD; ls c:; echo TAIL");
const output = await shell.invoke();
console.log(output); // "HEAD\nTAIL"
```

The echoes come through, but the ```ls``` output is still missing.

**Experiment  2**

```javascript
const shell = new Shell({ debugMsg: false });
await shell.addCommand("& { echo HEAD; ls c:; echo TAIL } | ConvertTo-Json -Compress");
const output = await shell.invoke();
console.log(output); // "[\"HEAD\"",\"TAIL\"]"
```

Again, just the ```ls``` output is missing.

**Experiment  3**

```javascript
const shell = new Shell({ debugMsg: false });
await shell.addCommand("&{ echo HEAD; Get-UICulture; echo TAIL } | ConvertTo-Json -Compress");
const output = await shell.invoke();
console.log(output); // "[\"HEAD\",{\"Parent\":{\"Parent\":\"\",\"LCID\":9 ... },\"TAIL\"]"
```

Hmm, the ```Get-UICulture``` output is there (I show it truncated in the comment above), so why doesn't ```ls``` (aka, ```Get-ChildItem```) also come through?

It seems some kinds of output is being dropped, but not others.  Any idea what is going on?

**Comment by mattflix** [comment]
Could the behavior reported in this issue possibly related to that reported in #20?

**Comment by BenjaminMichael** [comment]
I do not think ls c: means what you think it means in powershell.  I think you want
ls C:\

it works for me in this example:

```javascript
const powershell = require('node-powershell')
 let ps = new powershell({
        executionPolicy: 'Bypass',
        noProfile: true
    });   
    ps.addCommand(`ls C:\`) /* ps.addCommand("ls C:\\") also works */
    ps.invoke()
    .then(output => {
        console.log(output)
    })
    .catch(err => {
        console.log(err);
        ps.dispose();
    });
```

**Comment by mattflix** [comment]
Okay, I see that "ls c:" and "ls c:\" do list out different things.

But, that's beside the point.

The point is, when entered manually at the command-line, both commands output _something_.  But, with node-powershell, the output of "ls c:" is an empty string.  That is the problem here... this missing output.  No?

Or, does what you talk about above (somehow indirectly) explain the reason why the output of "ls c:" via node-powershell?  You've shown that "ls c:\" should work, but not why "ls c:" does not (that I can see).

Could you elaborate?

**Comment by BenjaminMichael** [comment]
I think you're experiencing a problem because youre attempting to use async/await and not the method described in the documentation

```javascript
ps.invoke().then(output => {}).catch(err => {});
```

**Comment by mattflix** [comment]
@BenjaminMichael, manually calling `.then()` or letting `await` do it yields equivalent code.  This has nothing to do with the behavior.

In any case, I have tried my old examples with the latest node-powershell (3.2) on my current version of Windows 10 (which is now build 1703; I was likely using an older build back when I filed this issue -- I was also using node-powershell 3.1).

In any case, I can no longer reproduce the behavior with either node-powershell 3.1 or 3.2 on Windows 10 1703.  Perhaps this was a problem running on an older version of PowerShell?

Here is my current version of PowerShell:
```
> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      15063  674
```

Perhaps the library author should try my original examples on older versions of PowerShell to see if he can reproduce the behavior?

If the behavior is PowerShell version-related, and no longer occurs on later versions, the author may still wish to ensure that users of older versions of PowerShell don't run into this problem (that perhaps can be avoided or worked-around with a change to node-powershell).  Or, at least warn them that a minimum version of PowerShell is required for proper behavior.

**Comment by BenjaminMichael** [comment]
If you could provide a full example I can test it for you but I cant get your examples above to compile when I add `const Shell = require('node-powershell')`

Could you provide a full example?  I apologize for my ignorance.

**Comment by mattflix** [comment]
Yes, my examples were just snippets, to compare the use-cases I was showing.

The complete version of my first example would be:

```javascript
const Shell = require('node-powershell');

async function main() {
    const shell = new Shell({ debugMsg: false });
    await shell.addCommand("ls c:");
    const output = await shell.invoke();
    console.log(output);
}

main();
```

This should run as-is with later versions of Node (which support `async` natively).

**Comment by BenjaminMichael** [comment]
Do you only want to test old versions of PS since this is not expected to work on old versions of Node?
