### ISSUE TITLE
"EOI" marker matching logic often "eats" last chunk of output

### ISSUE THREAD

**Issue by mattflix** [rannn505/node-powershell#26]
Software used:
* node-powershell 3.1.1
* node 7.9.0
* PowerShell 5.1.14393.1198
* Windows 10 (1607)

I have debugged and discovered that the code in node-powershell that matches the internal End-of-Input (EOI) marker can blindly throw away entire swaths of output just because it is emitted as part of the same data chunk that happens to contain the characters "EOI":

Excerpt from Shell.js
```javascript
    _this._proc.stdout.on('data', function (data) {
      if (data.indexOf(EOI) !== -1) {
        _this.emit(_type, _output.join(''));  // <== Any other output in "data" is lost here.  :(
        _output = [];
        _type = '_resolve';
      } else {
        _this.emit('output', data);
        _output.push(data);
      }
    });
```

I have definitely seen cases where ALL of the expected output of a command appeared in the same chunk as the "EOI" marker.  In these cases, the entire output is simply lost (even though node-powershell goes on to complete the request successfully).

I made the following modification, and started getting a lot more expected output:

```javascript
    _this._proc.stdout.on('data', function (data) {

      // BEGN OLD
      // if (data.indexOf(EOI) !== -1) {
      // END OLD

      // BEGIN NEW
      var offset = data.indexOf(EOI);
      if (offset !== -1) {
        data = data.substr(0, offset); // <== Grab any output before the "EOI" marker
        _this.emit('output', data);    // <== and process it
        _output.push(data);            // <== as usual.
      // END NEW

        _this.emit(_type, _output.join(''));
        _output = [];
        _type = '_resolve';
      } else {
        _this.emit('output', data);
        _output.push(data);
      }
    });
```

An even further improved implementation might:
* use something more unique than just the characters "EOI" (perhaps a GUID), and
* also carefully preserve ANY output that is part of the EOI chunk, not just the stuff that appears before the EOI marker (which is all my experimental modification above does).  In theory, there might also be some more output *following* the EOI marker too (that is part of the output of another command) which, I would assume, should be grabbed and added to the ```output``` for the _next_ command.

Also, note that issue #20 might be due to, and at least related to, this behavior.

**Comment by RongoDog** [comment]
I am think I am experiencing this very issue. I lose large chunk of output intermittently.
