### ISSUE TITLE
Race condition with reset of _self._cmds in invoke().

### ISSUE THREAD

**Issue by mattflix** [rannn505/node-powershell#28]
The ```invoke()``` function only clears the internal ```_self._cmds``` array of "added" commands upon asynchronous completion of the PowerShell execution of the commands.  This sets up a race condition with other command executions.

In certain circumstances, it is possible for additional commands to be added and ```invoke()``` called again before the processing of the previous ```invoke()```has completed -- and before node-powershell has cleared the ```_cmds``` array.  In these cases, the secondary ```invoke()``` calls "inherit" and extend the current contents of ```_cmds``` array already being processed by the original ```invoke()``` call.

In short, this race condition can result in PowerShell commands being executed multiple times and other unexpected chaos.

I quite easily ran into this in a project I was working on, where node-powershell was being hosted on a remote machine with ```addCommand()``` and ```invoke()``` calls being sent to it.  Throw in any moderately long-running command (thus causing ```invoke()``` to take some time to complete), and the race condition is exposed.

The fix would appear to be to eliminate the race condition by simply clearing the ```_cmds``` array earlier, as the PowerShell command is submitted, rather than after it completes.

Like so:

```javascript
      var _self = this;
      return new Promise(function (resolve, reject) {
        var _cmdsStr = _self._cmds.join('; ');

        // NEW
        // To avoid races, the commands array should be cleared up-front, here:
        _self._cmds = [];
        // END

        _self.__print__(OK_MSG, 'Command invoke started');
        _self._cfg.debugMsg && console.log(' ' + colors.gray(_cmdsStr));

        function resolve_listener(data) {
          _self.__print__(OK_MSG, 'Command invoke finished\n');
          reset();
          return resolve(data);
        }
        function reject_listener(error) {
          _self.__print__(ERROR_MSG, 'Command invoke failed\n');
          reset();
          return reject(ERROR_MSG(error));
        }
        function reset() {
          _self.removeListener('_resolve', resolve_listener);
          _self.removeListener('_reject', reject_listener);

          // OLD
          // Clearing it here (the current code) is way too late and creates race conditions.
          // _self._cmds = [];
          // END
        }

        _self.on('_resolve', resolve_listener);
        _self.on('_reject', reject_listener);

        _self._proc.stdin.write(_cmdsStr);
        _self._proc.stdin.write(os.EOL);
        _self._proc.stdin.write('echo ' + EOI);
        _self._proc.stdin.write(os.EOL);
      });
```

It might also be helpful for node-powershell to internally serialize multiple asynchronous```invoke()``` executions (perhaps with some kind of "operation queue"), since the target PowerShell process can only process one invocation at a time.

The node-powershell API also isn't helping out here, by separating into independent and potentially "racy" steps (```addCommand()``` and ```invoke()```) what really should be tied together.  An improved API might instead provide a way to build a set of "commands" as an entity, which can then be specifically "invoked" (with no possible confusion with other any commands, as can occur with the current API).

Usage might look like this:

```javascript
    let shell = new Shell();
    let commands = new shell.Commands();
    await commands.add('echo Now I can');
    await commands.add('echo build my commands');
    await commands.add('echo as a unit');
    let output = await commands.invoke();
```

**Comment by rannn505** [comment]
Hey @mattflix,

You are right about cleaning up the array of commands and in the next version I will clean it immediately after receiving the confirmation that it has passed to the PS treatment.

With regard to race condition, the library is based on promises and therefore, using the existing API, it is very easy to avoid the situation you described.

Thank you very much for turning my attention. 💯 👍

**Comment by mattflix** [comment]
Yes, it is not very "difficult" to avoid the race, but the race is created entirely by the design of the existing API.

Due the current API, every library client must:
a) first be aware that there may be a problem (which they may not be until strange behavior emerges, possibly after they have shipped their code),
b) debug and understand the problem, and
c) possibly write extra code to ensure that any group of addCommand() call(s) and the final invoke() call are always executed as an "atomic" operation.

So, my feedback is that, a slightly different API design (like the one I proposed) would eliminate the possibility for the race altogether, rendering moot concerns a), b), and c), making the library that much more robust and reliable.
