### ISSUE TITLE
Trouble Passing multiple parameters to PowerShell Script

### ISSUE THREAD

**Issue by Jitender-Yadav** [rannn505/node-powershell#29]
I want to pass multiple parameters to my powershell Script file, but it is giving me errors . I am not able to figure out what I am doing wrong.

**script.js**

let params = [{name: 'KeyStorePassword_', value: "iddfggdff@96"},
                    {name: '$KeyAlias', value: 'key454'}
    ]
    ps.addCommand('./WrappingPowerShellScript.ps1',params)
    ps.invoke()

 **WrappingPowerShellScript.ps1**

param (
    [Parameter(Mandatory = $true)]
    [string]$KeyStorePassword_,
    [string]$keyAlias
    
)

**Comment by BenjaminMichael** [comment]
Sorry Im not a total expert but I was wondering if it would work for you like:
let params = [{KeyStorePassword:"iddfggfdd@96"},{KeyAlias:"key454"}]

with


param (
[Parameter (Mandatory=$True,Position=0)]
[string]$KeyStorePassword,
[Parameter (Mandatory=$True,Position=1)]
[string]${KeyAlias
)

**Comment by BenjaminMichael** [comment]
You have a typo here otherwise your code works perfectly:
```javascript
{name: '$KeyAlias', value: 'key454'}
//should be
{name: 'KeyAlias', value: 'key454'}
```

**Comment by BenjaminMichael** [comment]
node-powershell also supports this syntax:
```javascript
let params = [{KeyStorePassword_: "iddfggdff@96"},{KeyAlias: 'key454'}
```

works fine in node-powershell 4

**Comment by rannn505** [comment]
Closes due to inactivity
