### ISSUE TITLE
No console logs

### ISSUE THREAD

**Issue by MystK** [rannn505/node-powershell#30]
Is there a way to make NPS run silently? Without any logs to the console?

**Comment by Maxvien** [comment]
Set `debugMsg: false` 😄 

`let ps = new shell({
    executionPolicy: 'Bypass',
    debugMsg: false
});`

**Comment by rannn505** [comment]
Hey @MystK,

@Maxvien offered an excellent solution ... try to use it. 💯

Let me know if you need further help :)
