### ISSUE TITLE
new-webserviceproxy isn't supported

### ISSUE THREAD

**Issue by im2nguyen** [rannn505/node-powershell#32]
does node-powershell/powershell 6.0 support new-webserviceproxy?

if not, is there a way to rollback node-powershell to powershell 5 so it does support this cmdlet? 

in powershell you can run previous versions of it, using "powershell -version 5 'echo test'", but for some reason, I can't do it here

Thanks!

**Comment by im2nguyen** [comment]
I attempted to add "-version 5" to the _args variable in /dist/Shell.js but it returns {"code": "EPIPE"}

**Comment by BenjaminMichael** [comment]
```javascript
const powershell = require('node-powershell')
 let ps = new powershell({
        executionPolicy: 'Bypass',
        noProfile: true
    });   
    ps.addCommand(`$PSVersionTable.PSVersion`)
    ps.invoke()
    .then(output => {
        console.log(output)
    })
    .catch(err => {
        console.log(err);
        ps.dispose();
    });
```
Can you run this script and share the console output with us?

PS requires WMF and probably more so I can't imagine that is an accurate statement that node-powershell uses a different version of PS than is installed for you all the time.
