### ISSUE TITLE
Electron packaging with --asar argument

### ISSUE THREAD

**Issue by PedroMordeP** [rannn505/node-powershell#36]
Hi, 
I think this is not an issue of the node-powershell but a limitation.

I have packaged my electron application with electron-packager with parameter --asar . (If I don't use asar argument it works.)
When using the app, I'm unable to execute PowerShell scripts because all the files are inside an app.asar file.
I already use the path variable like
`ps.addCommand(path.join(__dirname, "/scripts/testing.ps1"), [ ....... ]);`

I think I know the answer but Is it possible to use scripts inside that file?
Anyone know any alternative to hide the scripts?

**Console Error**
`[MYPATH]\resources\app.asar\scripts\testing.ps1` is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by BenjaminMichael** [comment]
> Though asar archives are treated as directories, there are no actual directories in the filesystem, so you can never set the working directory to directories in asar archives.
source: https://electronjs.org/docs/tutorial/application-packaging

**Comment by PedroMordeP** [comment]
That was my solution when I post the questions, i was hopping someone had done something different. I exclude the scripts folder and all the working files associated with their execution.
Thank you for the replay.

**Comment by BenjaminMichael** [comment]
One other suggestion is you can make the powershell commands in JS and addCommand one line at a time so yo never use external .ps1
