### ISSUE TITLE
Installing SharePoint Online Management Shell

### ISSUE THREAD

**Issue by moonweazel** [rannn505/node-powershell#38]
I am currently building a MS Bot which can run 'normal' PS scripts.  I really want to have the bot run SharePoint Online scripts but this needs the specific management shell to be installed.

Can your module do this?  Is it possible?

Cheers!

**Comment by BenjaminMichael** [comment]
Yeah you can do it.  In a project Im working on I use a Poweshell Module called "PowerShell Access Control" and it works as long as the module is located in either C:\Program Files\WindowsPowerShell\Modules or inside the Poweshell diectory in the profile of the usercontext the script is executing in.  something like C:\Users\userName\Documents\WindowsPowerShell\Modules

You can include this module in your project directory and then use node-PowerShell or whatever NPM module to make sure its in place for example:
```powershell
if (Test-Path "C:\Program Files\WindowsPowerShell\Modules\SharePointOnlineManagementShellModuleName"){<# its there #>}else{<#need to copy it there #>}
```

Keep in mind you need admin access to copy a module into C:\Program Files\WindowsPowerShell\Modules

**Comment by rannn505** [comment]
Closes due to inactivity
