### ISSUE TITLE
node-powershell was unable to start powershell

### ISSUE THREAD

**Issue by stevenzeck** [rannn505/node-powershell#39]
I'm adding a feature to [Atom Beautify](github.com/Glavin001/atom-beautify) to support formatting PowerShell files/text using [PowerShell Beautifier](https://github.com/DTW-DanWard/PowerShell-Beautifier).  I came across this package to be able to run the PowerShell module needed for this to happen, however I'm running into this error: `Opss... node-powershell was unable to start PowerShell.  Please make sure that PowerShell is installed properly on your system, and try again.`, and a separate message: `'powershell' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.` I'm on a Mac and have installed PowerShell via Homebrew.  Atom-Beautify is currently written in CoffeeScript, so the syntax is a little different but here is my code.  The relevant part is in the beautify function where it errors out on `ps = new shell()`.  It's all WIP (and just started)

```
"use strict"
Beautifier = require('./beautifier')
shell = require('node-powershell')

module.exports = class PowerShellBeautifier extends Beautifier
  name: "powershell-beautifier"
  link: "https://github.com/DTW-DanWard/PowerShell-Beautifier"

  options: {
    PowerShell: false
  }

  beautify: (text, language, options) ->
    ps = new shell()
    tempFile = @tempFile("input", text)
    ps.addCommand("Set-PSRepository -Name PSGallery -InstallationPolicy Trusted")
    ps.addCommand("Install-Module -Name PowerShell-Beautifier")
    ps.addCommand("Edit-DTWBeautifyScript " + tempFile)
    ps.invoke().then(=> @readFile(tempFile)).catch(err => {})
```

**Comment by szeck87** [comment]
PS to invoke powershell from the terminal (at least with my install) you have to run `pwsh` and not `powershell`, perhaps that's why?

**Comment by BenjaminMichael** [comment]
what versions of: node, Mac OS, node-powershell, and powershell are you on?

I would mostly be worried about what modules and/or dotnetlibraries that beautifier is dependent upon because youre using powershell on a mac.

**Comment by szeck87** [comment]
Node:  8.9.1
MacOS:  10.13.1
node-powershell:  3.3.1
powershell:  6.0.0

**Comment by BenjaminMichael** [comment]
"PowerShell Core 6.0.0-beta.9 the binary for PowerShell Core was renamed from powershell.exe and powershell on Windows and Linux/Unix/macOS respectively to pwsh.exe and pwsh"
source: the internet

time for a pull request?

**Comment by BenjaminMichael** [comment]
Seems like you could make an environmental variable as a workaround but Apple had made that really tricky you have to make a plist (see https://apple.stackexchange.com/questions/106355/setting-the-system-wide-path-environment-variable-in-mavericks)

It might be easier to uninstall and reinstall 6.0.0-beta.2 or another version

**Comment by szeck87** [comment]
Any update on this?

**Comment by BenjaminMichael** [comment]
It took me a while to understand this issue.  They renamed it because Windows PowerShell and PowerShell-Core need to be able to run side by side.  For this reason it makes sense to just make it an optional parameter with the default being Windows Powershell.  I will make a PR soon but I just now sort of figured out this issue.

**Comment by szeck87** [comment]
@BenjaminMichael @rannn505 I see a PR was opened for this.  Any update?

**Comment by BenjaminMichael** [comment]
Can you try my fork and then report back to us if it meets your needs?

https://github.com/BenjaminMichael/node-powershell

**Comment by szeck87** [comment]
It does.  I created the shell like this (it's in coffeescript):

```
shell = require('node-powershell')
ps = new shell(usePwsh: true)
```

And it spawned fine.

**Comment by szeck87** [comment]
@BenjaminMichael @rannn505 any update on this?

**Comment by BenjaminMichael** [comment]
@szeck87 you might want to check out [](https://github.com/IonicaBizau/powershell)

It is based on node-powershell but a little cleaner/simpler.  Lacking test coverage but actively maintained and they already merged my pwsh by parameter PR.

**Comment by rannn505** [comment]
@szeck87 @BenjaminMichael ,
Hey friend sorry it took a long time, I was on a very long trip, I promise to look at everything that has happened since my last commit and to release a new version very soon. Thank you for your patience 🥇.

**Comment by szeck87** [comment]
@BenjaminMichael I gave that one a try, unfortunately I'm converting javascript to coffeescript and something is off as I keep getting `data is not defined` using that package.

**Comment by BenjaminMichael** [comment]
Just wait for Rann to merge my PR it shouldn't take long since its 1.5 lines of changes

**Comment by AntoninMartin** [comment]
@rannn505  Please can you merge this PR, cause everything works great except that.

Thanks :)

**Comment by aoighost** [comment]
@rannn505  could you please merge this
@BenjaminMichael could you please put this on NPM in the mean time

**Comment by BenjaminMichael** [comment]
@aoighost i published it as an npm package called node-powershellcore

**Comment by BenjaminMichael** [comment]
don't forget you need to pass a parameter to use PowerShell Core "pwsh" 
```javascript
shell = require('node-powershell')
ps = new shell(usePwsh: true)
```
