### ISSUE TITLE
Working with SecureString and PSCredential 

### ISSUE THREAD

**Issue by ZescherW** [rannn505/node-powershell#42]
I'm invoking a command that create a System.Security.SecureString object but I can't use the output to create a  System.Management.Automation.PSCredential object, because the returned value is a 'System.Security.SecureString' string literal.

Is it possible to add commands with SecureString and PSCredential objects as parameters or it's only can be done using a ps script?

Thanks in advance,

Zak.

**Comment by BenjaminMichael** [comment]
It sounds like you have it figured out.  Do it in PS or another means of communicating with .NET API

Node-powershell can return a JSON formatted string but thats about as fancy as you can get AFAIK.

**Comment by ZescherW** [comment]
Thanks for the answer. I'm using node-powershell for an automation tool and I'd like to get ride of any ps1 file. 

I have the following code implemented for creating an organizational unit, but when I execute it  it opens a windows dialog asking for credentials:

`private getCredentialsCommandString(username: string, password: string): string {
        let command = `(New-Object -typeName System.Management.Automation.PSCredential -argumentList ${username}, ` +
            `(ConvertTo-SecureString ${password} -asPlainText -force))`;

        return command;
    }

public async createOrganization(username: string, password: string) {
        let credentialsCommand = this.getCredentialsCommandString(username, password);
        let params = [{Name: "UIA_TestZak"}, {Path: "'OU=Workspace,DC=tdev,DC=local'"}, {Server: "10.9.26.1"},
            {Credential: credentialsCommand}, {ProtectedFromAccidentalDeletion: false}];
        this.ps.addCommand("New-ADOrganizationalUnit", params);
        return await this.ps.invoke();
    }`

So is there any way to execute commands with credentials without user interaction?

**Comment by BenjaminMichael** [comment]
Yes this is something you do in PowerShell.  cmdlets like Remove-ADGroupMember you can use 
```powershell
-Confirm:$false
```
example:
```powershell
Remove-ADGroupMember -Identity $group -Members $user -Confirm:$false
```

**Comment by ZescherW** [comment]
Thanks. You can close this issue :)
