### ISSUE TITLE
Add proper support for multi-line PowerShell strings

### ISSUE THREAD

**Issue by suprak** [rannn505/node-powershell#44]
For example, this is a valid PS string

```
$x = @"
foo
bar
"@
```

However `node-powershell` does not support it because the `@` symbol is used for its parameter mechanics.

**Comment by BenjaminMichael** [comment]
I'm writing a PR for this but its going to take some time because it will need so much testing

**Comment by suprak** [comment]
👍 

If I were you, I would abandon the parameter feature of `addCommand`. There are a lot of complicated cases and with the advent of [string template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), the user can figure out their own parameter passing mechanism pretty easily.

**Comment by BenjaminMichael** [comment]
I agree and you can essentially bypass it by just passing in one string for example:

```javascript
ps.addCommand(`./remove-adGroupMember.ps1 -user '${user2}' -group '${groupDN}' -i ${i}`);
```

for me I would rather use string template literals but I always imagined thered be some use case where the developer has lots of JSON feeding in commands and parameters and this is somehow less typing or something

**Comment by BenjaminMichael** [comment]
I have a fork of node-powershell and I made a new branch: multi-line-suppor

https://github.com/BenjaminMichael/node-powershell/tree/multi-line-suppor

it seems to be working for this basic example:
```javascript
const powershell = require('./node-powershell');

let ps = new powershell({
    executionPolicy: 'Bypass',
    noProfile: true,
    multiLine: true
    });
    ps.on('output', output => {
        console.log(output);
    })
    ps.addCommand(`$x = @"`);
    ps.addCommand(`foo`);
    ps.addCommand(`bar`);
    ps.addCommand(`"@;`);
    ps.invoke()
    ps.addCommand(`$x | out-host`)
    ps.invoke()

let ps2 = new powershell({
    executionPolicy: 'Bypass',
    noProfile: true
}); 
ps2.addCommand(`$PSVersionTable.PSVersion`);
ps2.addCommand(`$PSVersionTable.PSEdition`);
ps2.invoke()
.then(output =>  {
    ps2.dispose();
    console.log(output);
})

```
results in
```terminal
NPS>  Process 5928 started

NPS>  Command invoke started
NPS>  $x = @"
foo
bar
"@;
NPS>  Command invoke started
NPS>  $x | out-host
NPS>  Process 240 started

NPS>  Command invoke started
NPS>  $PSVersionTable.PSVersion; $PSVersionTable.PSEdition
foo
bar

NPS>  Command invoke finished


NPS>  Command invoke finished

NPS>  Command invoke finished


Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  1944
Desktop



NPS>  Process 240 exited with code 0
```

I gotta learn how to write tests so I can write tests for it

**Comment by suprak** [comment]
I don't see the benefit of creating a call to `addCommand` per line. That seems unnecessarily repetitive.

What I was trying to do,

```js
addCommand(`
$value = @"
${JSON.stringify(req.params)}
"@
`);
```

**Comment by BenjaminMichael** [comment]
That seems more of an implementation detail.  This example works and it takes any number of commands separated by commas so I added an out-host command to show its working.  It seems to work.

```javascript
const powershell = require('./node-powershell');

const addThenInvokeMLCommand = (...multiLineCommand) =>{
    this.ps = new powershell({
        executionPolicy: 'Bypass',
        noProfile: true,
        multiLine: true
        });
    this.ps.on('output', output => {
        console.log(output);
    });
    this.ps.on('end', code => {
        this.ps.dispose();
    });
    multiLineCommand.forEach((line) => {
        const commandArray = line.split('\n');
        commandArray.forEach((val) => {
            this.ps.addCommand(val + `\n`);
        });        
    });
    this.ps.invoke();
}


const myJSON = {
    "name":"John",
    "age":30,
    "cars":[ "Ford", "BMW", "Fiat" ]
    }

addThenInvokeMLCommand(`
$value = @"
${JSON.stringify(myJSON)}
"@
`, `$value | out-host`);
```
