### ISSUE TITLE
ps.dipose() does not work in all instances

### ISSUE THREAD

**Issue by ASBaj** [rannn505/node-powershell#46]
Hi,

Just wanted to let you know that I have found that ps.dipose, which I call in then() of ps.invoke() does not dispose the shell in every case, though it does work in most cases. Even if I call ps.dispose().then(), and then return my promise, the shell still sometimes remains open. I am unsure of why.

Please let me know if I could provide you with additional details.

Thank for for making this module.

**Comment by BenjaminMichael** [comment]
Can you share the version of node-powershell you are using?  Significant inconsistency was ironed out in a recent release.

Secondly, can you provide some sample code?  [I have a basic demo that illustrates how I use ps.dispose() along with slightly complex operations here](https://github.com/BenjaminMichael/node-powershell-electron-basic-demo).

Beyond that, there are ways to derail the process so your .then(), .catch(), etc never happen.  The most obvious one for me was sending too few or too many parameters to my .ps1 scripts.  I could be wrong but I think this has to do with invoking a powershell command from the command line.  PowerShell can handle errors but the command line itself I'm guessing cannot in this case.  This is a real thing but the least likely thing to be your problem.  You can identify this problem by looking at the output of your program it will not say "command invoke finished" but will say "Process 1234 has exited"

**Comment by ASBaj** [comment]
Hi Benjamin,

I can confirm I am using version 3.3.1, which I believe is the latest.

Some example code:

```
function RunPSCommand(commandSyntax){
  return new Promise((resolve, reject) => {
    var ps = new powershell({ //Create a new shell each time, otherwise multiple commands don't work.
    executionPolicy: 'Bypass',
    noProfile: true
  });
  ps.addCommand(commandSyntax);
  ps.invoke()
  .then(output => {
    ps.dispose()
    .then(() => {
      return resolve(output);
    });
  })
  .catch(err => {
    ps.dispose()
    .then(() => {
      return resolve(err);
    });
  });
});
}
```

I then invoke this from other functions.

I'm only using 1 powershell command thus far: Get-VM <VMName> | ConvertTo-JSON -Compress.

The output of my program shows "Process XXXX has started", but does not show a finish. When I stop my program, the PowerShell Windows than also stops.

I should probably mention also that I am running the application as a service through the use of the "node-windows" module. I don't know if this affects your module inadvertently.

Let me know if I can provide anything else. Thanks!

**Comment by BenjaminMichael** [comment]
Please try to pipe your commands to out-host.  Node-powershell reads the output to the console it doesnt just get to directly access variables.  You will want to json.parse your output variable.

**Comment by ASBaj** [comment]
Hi benjamin,

After trying your suggestions, and a few other things, I am strongly inclined to think that this is not a problem with your module, but with Node.js in general. PS.Dispose() would work if the code was actually reaching that point, but I'm not inclined to think it is.

Thanks for your assistance.
