### ISSUE TITLE
your documentation page has nothing in it.

### ISSUE THREAD

**Issue by RLeverich** [rannn505/node-powershell#47]

**Comment by rhulet34** [comment]
Yeah its empty

**Comment by BenjaminMichael** [comment]
This appears to be an issue with github pages which is hosted in a free cdn called rawgit which has no uptime guarantees.  I can try and provide some kind of mirror if I can find a cached copy on one of my computers which I think I can but its almost 5PM Friday so it might take until tomorrow.

**Comment by BenjaminMichael** [comment]
You can see a basic example on his page here:
http://rannn505.github.io/node-powershell/

**Comment by BenjaminMichael** [comment]
SOLVED:

I see whats happening here.  When you visit https://cdn.rawgit.com/rannn505/node-powershell/236b6c3a/docs/docs.html click on the tiny black shield on the right side of the ominibox (the url bar) and load external scripts.  The https cert is expired or some such nonsense.

**Comment by BenjaminMichael** [comment]
In FireFox you click on the i on the left side of the URL bar, then click the arrow pointint right, then disable protecton

**Comment by joanjane** [comment]
You should change your [external resources](https://github.com/rannn505/node-powershell/blob/master/docs/docs.html#L12) from http to https. This will load the resources safely and seems a trivial task. It's not a good idea to advice people to disable any protection on browsers.

Cheers

**Comment by alogwe** [comment]
I had used the permissions workaround before, but now it seems there's a 404 error when loading the flatdoc.js library at https://cdn.rawgit.com/rstacruz/flatdoc/v0.9.0/flatdoc.js

**Comment by alogwe** [comment]
@andolojm Thanks so much!
