### ISSUE TITLE
Executing scripts with special characters on the path

### ISSUE THREAD

**Issue by PedroMordeP** [rannn505/node-powershell#48]
Hi,

I'm trying to invoke the following command

& 'C:\folder\folder\ãpplic ation\scripts\script.ps1'

I know the issue is on the "ã" but i'm not able to find a solution to escape this.

Error 

> & : The term 'C:\folder\folder\ãpplic ation\scripts\script.ps1' is not recognized as 
> the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
> included, verify that the path is correct and try again.

I tried things like 

`& (Convert-Path -LiteralPath 'C:\folder\folder\ãpplic ation\scripts\script.ps1')`

or 

```
$command = Convert-Path -LiteralPath 'C:\folder\folder\ãpplic ation\scripts\script.ps1';
& $command
```

But i get the error

> Cannot find path 'C:\folder\folder\ãpplic ation\scripts\script.ps1' because it does not exist

When executing on the powershell command line this work but using the node-powershell to invoke the command does not.
Someone have any way to resolve this?

**Comment by BenjaminMichael** [comment]
This question has been answered in many places.  Windows doesnt use UTF-8 in the terminal by default.  See [https://github.com/intellij-rust/intellij-rust/issues/766](https://github.com/intellij-rust/intellij-rust/issues/766)
