### ISSUE TITLE
Usage with webpack

### ISSUE THREAD

**Issue by jackdh** [rannn505/node-powershell#49]
Hey,

So I've used webpack "file-loader" to load my powershell,

> http://localhost:1212/dist/9d67ce14b061421ea6486929162ddaee.ps1

with 

> import powershell with "../../example/powershell.ps1"

then attempt to use it with 

```
let ps = new Powershell({
      executionPolicy: 'Bypass',
      noProfile: true
    });

    ps.addCommand(powershell, [{ GigaWatts: 1.0 }]);
```

I get

> is not recognized as the name of a cmdlet, function,  script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

I'm guessing I'll need to read in the file then paste it as string into the command to bypass this but it would be great if it supported it.

**Comment by BenjaminMichael** [comment]
For complex scripting I reccomend you write out the parameters yourself using template literals and pass it as a single string.

```javascript
let scriptY = "./psexample.ps1",
paramX = "banana"
ps.addCommand(`${scriptY} -myParam '${paramX}' 
ps.invoke()
```

**Comment by jackdh** [comment]
Hey thanks for the quick reply. Sorry I realized i'd made some spelling mistakes in the original question.

So I'm using your plugin within Electron and would like to be able to package the powershell scripts within the application its self. 

Currently I'm attempting to get webpack to package these scripts up (which does work with the file-loader, if I visit that url in my original question I can see the output on the .ps1 file displayed) so that they are pulled in with the buillt application. I'm using the Electron-React-Boilerplate if that helps.

Does that make anymore sense?

**Comment by BenjaminMichael** [comment]
This issue has been raised and closed see #36 

I use electron and I just make a zip file out of my project with my scripts included in the zip file.  This is really a "problem" for PowerShell that you want it to execute precompiled scripts in non human readable format.  Also note that asar electron apps can be unpacked extremely easily so you cant hide secrets in there.

**Comment by BenjaminMichael** [comment]
Note that hashing is the appropriate way to store passwords.  You can use a library for example bcrypt
https://www.npmjs.com/package/bcrypt

**Comment by jackdh** [comment]
So I'm not trying to obscure them at all, they just end up in the asar file as Electron-build will but the "files" within the .asar. 

I can see them in there when I open the asar up however I'm struggling to get a reference to them within the code to load them into .addCommand(); as it is always coming back undefined. Hence I attempted to use the Webpack file loader to do the importing, which it does however addCommand does not like it in that format.

**Comment by BenjaminMichael** [comment]
Its probably best to copy your scripts with a post install gulp file

```javascript
var gulp = require('gulp');

gulp.task('copyscripts', function() {
    gulp.src('scripts/**.*')
    .pipe(gulp.dest('release-builds/projectName/scripts'));
 });

 gulp.task('default', ['copyscripts']);
```

**Comment by BenjaminMichael** [comment]
I guess file-loader is the webpack equivalent of this gulp task: https://github.com/webpack-contrib/file-loader

**Comment by BenjaminMichael** [comment]
@rannn505 feel free to close this and every other issue thats open currently for node-powershell
