### ISSUE TITLE
Spaces in path names to scripts don't seem to work

### ISSUE THREAD

**Issue by ariestav** [rannn505/node-powershell#5]
Hi There,
I'm unable to get Powershell to spawn with my script.  My path has a space in it and I'm not sure if that's tripping it up.  For example, this does not work:

````
var PS = require('node-powershell');
var shell = new PS('C:\\Path\\To\\My Favorite\\Directory\\test.ps1');
````
Nor does the following work
````
var PS = require('node-powershell');
var shell = new PS('C;/Path/To/My\ Favorite/Directory/test.ps1');
````

**Comment by rannn505** [comment]
Hey @ariestav 
Please check out the new features entered in the last commit, (the Shell.executionStringBuilder in this case) Some of them have been developed , inspired by the issues you have open , so thanks.
:+1:
