### ISSUE TITLE
Partial pipeline return

### ISSUE THREAD

**Issue by hsimah** [rannn505/node-powershell#50]
I love this library!

Is there any way to return pipeline output for a long running process? I need to query and update ACLs on remote machines. In a PowerShell window I use `Write-Output` to pass output down the pipeline. Is there a feature in this library to accomplish this, or are my users going to have to just wait for all the output at once?

**Comment by BenjaminMichael** [comment]
I know, isn't it fun to use node-powershell?  There's a few ways to accomplish what you are describing but I think the short answer to your question is the "on output" event listener:

```javascript
let ps = new shell({
            executionPolicy: 'Bypass',
            noProfile: true
            });
ps.on('output', output => {console.log(output)}
ps.addCommand(`./somescript.ps1`)
ps.invoke()
```

So what I do is have my script output some JSON formatted string that explains what step of the process or more frequently what async thing just completed.

**Comment by hsimah** [comment]
Clever. Thanks for that.

[See here for other events (where I should have looked).](https://github.com/rannn505/node-powershell/blob/a92458bb125bfcc528ed39382ffa23a610318701/docs/api.md)

**Comment by hsimah** [comment]
Looking at the source it seems to only emit the `output` event when EOI is reached - is there a way to get `Write-Output` (or even `Write-Verbose`) output during the script running?

**Comment by BenjaminMichael** [comment]
Yeah you're right it doesn't work that way.  What I have always done is use PowerShell in a more atomic way so I run a small script that gathers a list and returns it to Javascript then I have Javascript iterate through the list entering in each value as a parameter in the next PowerShell operation.  In this way I would, for example, get-adprincipalgroupmembership and then get-effectiveaccess for each of those groups.  In my experience this is best done one at a time in series and then you ps.dispose() at the end.

I have a very basic example here: https://github.com/BenjaminMichael/node-powershell-electron-basic-demo
