### ISSUE TITLE
The sample code in the read-me is missing a ps.dispose() call in the success case

### ISSUE THREAD

**Issue by mklement0** [rannn505/node-powershell#51]
If you try that code literally, executing hangs.

While the fix may seem obvious, people do get tripped up by this - see https://stackoverflow.com/q/50967442/45375

**Comment by BenjaminMichael** [comment]
Makes sense for the readme example but starting out I actually found the opposite more confusing when working on anything nontrivial.  Basically any time I have used node-powershell I have used the object for more than one PS command invocation and not disposing the object is much much faster than creating a new object every time.  I don't find that I need to dispose of the object on errors either.

**Comment by mklement0** [comment]
@BenjaminMichael: 

It is crucial that sample code works as-is, so as not to confuse beginners.

* If there's a better - and concise - way to make sure the success case finishes processing, fix the sample to show _that_. (I can't tell, because the docs are broken, and I don't want to tinker with my browser's security settings just to make them work).

* Otherwise, use the simple `ps.Dispose()` approach and add comments or notes pointing to more advanced information.

**Comment by rannn505** [comment]
removed the dispose from both as I want people to understand that the process is still open.

**Comment by mklement0** [comment]
Note that https://rannn505.gitbook.io/node-powershell/start again shows `ps.dispose()`, and only in the `.catch()` call, again inviting confusion.

If the intent is to show that the process remains open to service more commands later, at least a comment is called for.
