### ISSUE TITLE
How can I run the scripts under another user?

### ISSUE THREAD

**Issue by dhuber666** [rannn505/node-powershell#53]
Hi guys,

I have to run some scripts with a different users. For example the Exchange Command:
`Add-MailboxPermissions` doesn't take a -Credential Parameter. 

But I have to provide it because the normal domain User has no rights for that command. If there is no way to run a script as could you give me a tip to solve this in another way? If I would start my IDE (Visual Studio Code) as another User and then run the app, the scripts should get run from that user, am I right?

**Comment by BenjaminMichael** [comment]
It sounds like you are doing this in Windows.  For Windows, you can do it the easy cheezy way and, like you said, run VS Code as another user to get their terminal or you can open the node command prompt as another user.  You can even run powershell as another user and have access to node.

To do it the hard way (again, for Windows) you want to look at[ this guide to Splatting ](https://ramblingcookiemonster.wordpress.com/2014/12/01/powershell-splatting-build-parameters-dynamically/)and [this guide](https://xainey.github.io/2017/powershell-electron-demo/#using-the-credential) has a section on putting it into practice.
