### ISSUE TITLE
String parameters with quotes hang shell

### ISSUE THREAD

**Issue by hsimah** [rannn505/node-powershell#54]
If a string containing a single (`'`) or double (`"`) quote is passed to `addCommand` the shell instance hangs. It is expecting a matching quote, which may or may not come. In `Utils.js` there is only a check for whitespace in strings.

PR to come.

**Comment by BenjaminMichael** [comment]
Can you give an example that is not solved by using backticks ``` `` ``` around your strings and is not typical of PowerShell's regular behavior?

**Comment by hsimah** [comment]
@BenjaminMichael do you mean me escaping my quotes before invoking PowerShell? If no, not really.

imo, I should be able to pass valid javascript strings to node-powershell and have it correctly format them for PowerShell.

I can see an argument for me having to escape the strings I pass to node-powershell too. I've done the work in my fork for my use case.

**Comment by BenjaminMichael** [comment]
No I'm saying use template strings which are new if you are unfamiliar with ES6.  It will give you the equivalent value as if you escaped characters
```
`\`` === '`' // --> true
```

**Comment by hsimah** [comment]
If I escape the javascript string myself (ie insert `` ` `` before my quotes) the command execute fine. I feel a javascript library should be doing the escaping for me, since I pass in a valid javascript string. The fix was a simple: `value.replace(/[\'\"]/g, '`$&');`.

In the current version this will hang:
```
string a = 'hsimah\'s';
string b = "hsimah's";
string c = `hsimah's`;
```
These will work:
```
string a = 'hsimah`\'s';
string b = "hsimah`'s";
string c = `hsimah\`'s`;
string d = 'hsimah\'s test'; // node-powershell wraps strings with whitespace in double quotes
```

**Comment by BenjaminMichael** [comment]
```
ps.addCommand(`write-host "hsimah's"`) //doesn't hang
```

This is just how PowerShell works.

**Comment by hsimah** [comment]
Yes but if you use the parameter/value syntax it does hang:

`ps.addCommand('my-cmdlet', [{Name: "hsimah's"}]); // hangs`

Node-powershell doesn't wrap the value in quotes unless it contains a space. PowerShell is inferring it is a string, but it needs to be escaped with a backtick.

**Comment by BenjaminMichael** [comment]
My opinions are not those of Rann.  I don't use the prams as JSON I just always use template strings.

```
ps.addCommand(`./scripts/get-ADUser.ps1 -u1 ${payload.user1Name} -cu ${payload.currentUser}`);
```
In this example I don't even use quotes because I already sanitized the user names Im gathering.  In my opinion these are merely implementation details.  Since you made your own fork and your PR like you have people will see it and if they like it they will ask you to make an npm module (because Rann doesn't actively maintain node-powershell anyways).

**Comment by hsimah** [comment]
Yeah, I considered template strings, but some of the cim cmdlets get out of hand with the number of parameters. The array of objects was easier to use in that regard.

I'll add a test to see if my fork affects the pure string commands. I don't think it would as the logic flow is different, but I didn't check that and it's a bad PR if I break your code!

**Comment by hsimah** [comment]
@rannn505 I see this was closed. I no longer use node-powershell (changed jobs). 

Is this fixed or not deemed necessary? I have an open PR related that can be closed either way.
