### ISSUE TITLE
Handling Execution Policy

### ISSUE THREAD

**Issue by ariestav** [rannn505/node-powershell#6]
Also, is it possible to set the ExecutionPolicy when calling the PowerShell, for example by using "bypass" option?

**Comment by speidy** [comment]
+1
בתאריך יום ב׳, 22 בפבר׳ 2016 ב-0:01 מאת Arie Stavchansky <
notifications@github.com>:

**Comment by rannn505** [comment]
Hey @ariestav 
Please check out the new features entered in the last commit,
Some of them have been developed , inspired by the issues you have open , so thanks.
:+1:
