### ISSUE TITLE
32 vs 64 bit dlls

### ISSUE THREAD

**Issue by NetanSolutions** [rannn505/node-powershell#60]
I have a module(3rd party module, not anything I have authored) that I use with PowerShell that is a 32bit dll, and I am running on a 64bit machine, so the instruction is to open with the 32bit ISE. This is the first time I am trying to use NodeJS to run my PS scripts, and I am getting the error "An attempt was made to load a program with an incorrect format", which on initial investigation seems to be related to this 32 vs 64bit clash. If anyone has any experience with this or has a workaround that would be hugely appreciated.

**Comment by BenjaminMichael** [comment]
node-powershell uses powershell.exe (or pwsh in the PSCore compatible fork)

you want to use the Powershell v 1 executable:
%SystemRoot%\syswow64\WindowsPowerShell\v1.0\powershell.exe

The workaround for you could be to clone this project, change powershell.exe to %SystemRoot%\syswow64\WindowsPowerShell\v1.0\powershell.exe in src\shell.js and then do the build process (type 'npm build' in the root of the project directory)

If more people express interest I will make an npm package call node-powershell-x86 but Im going camping this week so Im definitely not doing it any time soon.

**Comment by NetanSolutions** [comment]
Thanks for the reply, will look into this and enjoy your camping!
