### ISSUE TITLE
Possible to use Powershell attached with the application?

### ISSUE THREAD

**Issue by ALIENQuake** [rannn505/node-powershell#65]
Any clue which lines I need to edit in order to use Powershell attached with the application?

**Comment by BenjaminMichael** [comment]
shell.js is where you are going to change how node-powershell calls powershell.  You make the changes and then do an npm build and test it out.  I had to edit this file to make my branch where i am able to toggle using pwsh and powershell

**Comment by ALIENQuake** [comment]
@BenjaminMichael Thanks for pointing me where to look. I have some feedback regarding pwsh, should I posit it for you or wait until @rannn505 will release new prerelease?
