### ISSUE TITLE
How to handle errors?

### ISSUE THREAD

**Issue by IonicaBizau** [rannn505/node-powershell#7]
How to handle process error and stderr streams?

**Comment by rannn505** [comment]
Hey @IonicaBizau ,
Sorry for the long waiting, I was pretty busy lately.
So... I double check it, and what interesting us is the following lines in the `index.js` file of the module:
```javascript
    _proc.stderr.on("data",function(data) {
        _shell.emit('output', data);
    });
    _proc.on('close', function (code) {
        _shell.emit('end', code);
    });
```
Those lines means that:
- if the process outputs and error to the stderr stream, you will get if you listen to the `on.output` event.
- if there is a process error, you will get a `1 code` if you listen to the `on.close` event.

Let me know if you managed to solved this, or you need further help .. 
I'd love you to add a star to the project :)
GL and THx :+1:

**Comment by rannn505** [comment]
Hey @IonicaBizau ,
Sorry for the long waiting, I was pretty busy lately.
So... I double check it, and what interesting us is the following lines in the `index.js` file of the module:
```javascript
    _proc.stderr.on("data",function(data) {
        _shell.emit('output', data);
    });
    _proc.on('close', function (code) {
        _shell.emit('end', code);
    });
```
Those lines means that:
- if the process outputs and error to the stderr stream, you will get if you listen to the `on.output` event.
- if there is a process error, you will get a `1 code` if you listen to the `on.close` event.

Let me know if you managed to solved this, or you need further help .. 
I'd love you to add a star to the project :)
GL and THx :+1:

**Comment by IonicaBizau** [comment]
@rannn505 Thanks for feedback. I created a new project based on this, where I added the `error-output` event (among other little things): https://github.com/IonicaBizau/powershell

What is strange is that the exit code is `0` even there is an error. It may depend on the command that is executed probably. I'm not a Windows user, but a friend needed this. :grin:
