### ISSUE TITLE
continually getting Command Invoke Failed

### ISSUE THREAD

**Issue by jhylton** [rannn505/node-powershell#75]
Hello,

I am trying to run a powershell script that does a lot of collection and currently writes a complex .json file with no problem. however when i invoke this i continually get "Command Invoke Failed". I am sure it comes down to how i am trying to return the object. 

# writing out our report
$report | add-member -membertype NoteProperty -Name controls -Value $controls
$doc = $report | ConvertTo-Json -Depth 4
$doc | ConvertTo-Json -Compress
# $doc = $report | ConvertTo-Json -Depth 4
$obj = [PSCustomObject]@{name="obj"; value=$doc}
$obj | ConvertTo-Json -Compress
write-host $obj

how would i return a complex .json file back to node?

var runPowershell = (vcenter, tenant) => {
    return new Promise((resolve, reject) => {
        ps.addCommand('./controllers/vircenter.ps1 -vercenter ' + vcenter + ' -tenant ' + tenant);
        ps.invoke().then(output => {
            console.log(JSON.parse(output));
            ps.dispose();
            resolve(output);
        }).catch(err => {
            console.log('there was an error', err)
            ps.dispose();
        });
    });
}

the error i get back looks something like this:

Property "Values" cannot be found.Property "Values" cannot be found.Property "Values" cannot be found.Property "Values" cannot be found.{"name":"obj","value":"{\"Attrib1\":\"value1\",\"Attrib2\":\Value2\",\"Attrib3\":\"Value3\"},{\"newAttrib1\":\"Value2\",[{\"array1\":\"arrVal1\"}]

any help would be greatly appreciated! 

Many thanks!

**Comment by BenjaminMichael** [comment]
Can you give an example of your complex JSON?  I assume you want to nest objects.  I am guessing that the problem is how your complex object is constructed, parsed into JSON by powershell, or parsed from string to object by JSON.parse

**Comment by jhylton** [comment]
Here is a stripped down version of the current json that i am dealing with. it would look like this, however has more like 40 controls.

{
    "instanceId": "servername",
    "tenant": "test",
    "reportTime": "2019-01-29T10:56:38+01:00",
    "controls": [
        {
            "controlId": "control:01",
            "description": "my first description",
            "result": "Pass"
        },
        {
            "controlId": "control2:02",
            "description": "my description",
            "result": "Fail",
            "reason": "this is why there was a failure",
            "offenders":[
                {
                    "Offender": "offender1", "myValue": "value"
                },
                {
                    "Offender": "offender2", "myValue": "value"
                }
            ]
        }
    ]
}

**Comment by jhylton** [comment]
Hi there,

i tried another work around, but no luck. basically i am now trying to convert the .json file into a base64 encoded string and return this to the node application, but i still get the following error:

there was an error Property "Values" cannot be found.Property "Values" cannot be found.Property "Values" cannot be found.Property "Values" cannot be found.{"name":"obj","value":"ewANAAoAIAAgACAAIAAiAGkAbgBzAHQAYQBuAGMAZQB..."}

i wonder if I am missing something very basic here?

many thanks!!

**Comment by BenjaminMichael** [comment]
You are just missing the -depth parameter for convertto-json

```powershell
$example = @(
    @{
        "instanceId" = "servername"
        "tenant" = "test"
        "reportTime" = "2019-01-29T10:56:38+01:00"
        "controls" = @(
            @{
                "controlId" = "control:01"
                "description" = "my first description"
                "result" = "Pass"
            },
            @{
                "controlId" = "control2:02"
                "description" = "my description"
                "result" = "Fail"
                "reason" = "this is why there was a failure"
                "offenders" = @(
                    @{
                        "Offender" = "offender1"; "myValue" = "value"
                    },
                    @{
                        "Offender" = "offender2"; "myValue" = "value"
                    }
                )
          }
       )
    }
)

$example | ConvertTo-Json -Depth 4 | Out-Host
$example | ConvertTo-Json -Depth 3 | Out-Host
```

```terminal
{
    "reportTime":  "2019-01-29T10:56:38+01:00",
    "controls":  [
                     {
                         "description":  "my first description",
                         "controlId":  "control:01",
                         "result":  "Pass"
                     },
                     {
                         "offenders":  [
                                           {
                                               "Offender":  "offender1",
                                               "myValue":  "value"
                                           },
                                           {
                                               "Offender":  "offender2",
                                               "myValue":  "value"
                                           }
                                       ],
                         "reason":  "this is why there was a failure",
                         "description":  "my description",
                         "controlId":  "control2:02",
                         "result":  "Fail"
                     }
                 ],
    "tenant":  "test",
    "instanceId":  "servername"
}
{
    "reportTime":  "2019-01-29T10:56:38+01:00",
    "controls":  [
                     {
                         "description":  "my first description",
                         "controlId":  "control:01",
                         "result":  "Pass"
                     },
                     {
                         "offenders":  [
                                           "System.Collections.Hashtable",
                                           "System.Collections.Hashtable"
                                       ],
                         "reason":  "this is why there was a failure",
                         "description":  "my description",
                         "controlId":  "control2:02",
                         "result":  "Fail"
                     }
                 ],
    "tenant":  "test",
    "instanceId":  "servername"
}
```

**Comment by rannn505** [comment]
Closed due to lack of response
