### ISSUE TITLE
Question about data result in arrays

### ISSUE THREAD

**Issue by chris-neely** [rannn505/node-powershell#8]

**Comment by rannn505** [comment]
Hey @chris-neely ,
I was just about to answer your question.
Basically, the output obtained from the command you run, comes in as a type of string to the callback (the "output" var is a string), so thats why, when you try to access an index in this var (output[i]), you receives a signal letter from the whole string.
I would suggest you try one of the following:
- Try to parse the output var (string) to array or object type.
- Try to use the string manipulation functions to cut it properly and get the output you want.

Let me know if you managed to solved this, or you need further help .. 
I'd love you to add a star to the project :)
GL and THx :+1:

**Comment by chris-neely** [comment]
Thanks Rannn!  I was able to parse the results after doing a bit of research.  I appreciate your reply!
