### ISSUE TITLE
i found a very strange bug

### ISSUE THREAD

**Issue by FloatingShuYin** [rannn505/node-powershell#80]
I found a very strange bug. When using node-powershell in an electron app, changing the window size will block the loop.

It’s very easy to reproduce this bug.
In the main process:
```javascript
const {app, BrowserWindow, ipcMain} = require('electron')
const Shell = require('node-powershell')

const test = async () => {
  for (let index = 0; index < 1000; index++) {
    const ps = new Shell({
      executionPolicy: 'Bypass',
      noProfile: true
    })
    ps.addCommand(`echo ${index}`)
    try {
      const result = await ps.invoke()
      console.log('im result: %s', result)
    } catch (err) {
      console.log('err', err)
    } finally {
      await ps.dispose()
    }
    console.log('im index: %s', index)
  }
}
setTimeout(() => {
  test()
}, 2000)
```
I also created a repository to make it easier for you to reproduce it:
https://github.com/FloatingShuYin/electron-quick-start-node-powershell

Bug reproduction
Click on the Hello World title

Then change the window size

Then you will see that the expected loop is blocked

Does anyone know what happened?

**Comment by BenjaminMichael** [comment]
This is really more of an electron question.

In an electron app main.js and renderer.js are run as different processes. 

The main process is responsible for creating and managing BrowserWindow instances and various application events.  A subset of Electron APIs (see graphic below) are available in the main process, as well as all node.js modules. The docs state: “The basic rule is: if a module is GUI or low-level system related, then it should be only available in the main process.” (Note that GUI here means native GUI, not HTML based UI rendered by Chromium).

 If you put your node-powershell code inside of renderer.js then it will not be interrupted by the processing happening on the main thread.  I have a basic example [here](https://github.com/BenjaminMichael/node-powershell-electron-basic-demo).

**Comment by FloatingShuYin** [comment]
@BenjaminMichael Awesome! Thank you for your answer, it really is as you said.
i moved the code to the rendering process and it worked as expected.
And your answer gives me a deeper understanding of how electron works.
Thank you very much for your answer again.
i will close this issue.
