### ISSUE TITLE
encoding of output

### ISSUE THREAD

**Issue by albanm** [rannn505/node-powershell#82]
Hello,

From what I understand powershell and node-powershell should be communicating in utf8. But I get bugs with badly encoded chars. I run on a Windows ln french language.

This is the code:

```javascript
pshell.addCommand('$PSDDefaultParameterValues = @{"*:Encoding" = "utf8"}')    pshell.addCommand(`get-acl ${path} | Select-Object Access,Group,Owner | ConvertTo-Json`)    const aclStr = await pshell.invoke()
```
The string contains errors for characters with diacritics, for example a user name with a "é".

Any idea ?

**Comment by albanm** [comment]
In case other persons struggle with this, my solution was to set the powershell console output encoding like this:

```
pshell.addCommand(`[Console]::OutputEncoding = [System.Text.Encoding]::UTF8`)
```
I wonder if this lib could not do it automatically.

**Comment by lucahost** [comment]
did you had to invoke this each time or just once per pshell?
