### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by backtolife2021** [rannn505/node-powershell#84]
The code will cause this.streams.stderr to repeatedly listen for the same event:
```javascript
const Shell = require("node-powershell");

const test = async () => {
  const ps = new Shell({
    executionPolicy: "Bypass",
    noProfile: true
  })
  for (let index = 0; index < 10; index++) {
    ps.addCommand(`echo ${index}`)
    const res = await ps.invoke()
    console.log("im index and res: %n %s", index, res)
  }
}
 test()
```
![image](https://user-images.githubusercontent.com/24669431/56094983-b5727680-5f0a-11e9-9d5d-2714ea9013cf.png)

https://github.com/rannn505/node-powershell/blob/b0a0f7f33f7c0b07351e875007e97a20d217b420/lib/Shell.js#L174-L228

I have noticed that every time you run the invoke function, you will recreate the ShellStreamBuffer instance, this should be optimizable.
https://github.com/rannn505/node-powershell/blob/b0a0f7f33f7c0b07351e875007e97a20d217b420/lib/Shell.js#L180

**Comment by zenion** [comment]
pretty much hit this leak anytime i'm needing to run a powershell command and get back the output in a looped format... but even if i didn't as stated above, basically everytime we call invoke() we eat up a little memory that we never end up releasing. For me I'm simply using this in a 1-shot fashion so i'd be content with even the ability to inject as a config option to the frontend class of node-powershell the ability to set `emitter.setMaxListeners(n)` when its instantiated.

**Comment by rannn505** [comment]
@FloatingShuYin @zenion ,
A fix will be released with the next version.
working on that :)

**Comment by rannn505** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix MaxListenersExceededWarning](https://trello.com/c/zNLHUKtY/60-fix-maxlistenersexceededwarning)

**Comment by sopelt** [comment]
Thank you for your work @rannn505 ! Do you have an idea on when this might be released?
And has anyone looked into what issues might occur due to this? Is it 'just' a leak or is there functionality that is missing as soon as the limit is hit?

**Comment by rannn505** [comment]
@sopelt,
I'm aiming for Saturday 🤞

**Comment by rannn505** [comment]
@sopelt,
I still have some small things left before I can release, but I won't have enough time to fix them today.
I believe it will be released tomorrow.
Thank you for your patience.

**Comment by rajabilal555** [comment]
@rannn505 Is this fixed ? because im still having this issue on the latest Version from NPM and I also cant see any new releases on Github... 
I am also having the same issue and im using Node-Powershell to obtain information about processes every 5 seconds...
Hope this gets fixed soon.

**Comment by rannn505** [comment]
@sopelt take a look on:
https://github.com/rannn505/node-powershell/pull/116

Its not ready for publish but this is a good alpha :)

**Comment by dmilin1** [comment]
@rannn505 I'm currently facing this problem as well. In the meantime, is there any simple fix or workaround?

**Comment by sopelt** [comment]
hey @rannn505 , the branch looks like you went all in ;)
Is there a plan to rename the package or what does `node-shell` refer to?
I have built the branch locally, installed it in my project and started refactoring (mostly import, constructor options, result handling). Do you have any tips or are you aware of anything I should add to my configuration to get as close to the previous behavior as possible? ;)
Currently I am looking at why I see lots of `Expressions are only allowed as the first element of a pipeline.` in the errors ... and why I seem to have some newlines in stderr ...

**Comment by rannn505** [comment]
@sopelt 
![image](https://user-images.githubusercontent.com/11806915/79676572-1dc7f800-81f0-11ea-98c8-f457a4b46132.png)

Regarding the name thing, this version I implemented the NPS base classes with an abstract layer that would now allow me to apply a cover to any other shell I want quite easily and fast. The name of the package will not change but new packages (like node-bash etc ..) will be added very soon. All of them will be here in this repo (and I plan to use [lerna](https://github.com/lerna/lerna) to manage all the new packages). it will be fun :)

**Comment by sopelt** [comment]
Hi @rannn505 , I've seen that you published a new release/preview to npm? How far along is that? ;)
Sorry for not providing feedback yet. I've looked at using a local package a few weeks back but other tasks came up... :-/

I'll try to drop in the new version in our project this week.

**Comment by sopelt** [comment]
Hi @rannn505 .. I installed 5.0.0-next.1 and tried running https://github.com/rannn505/node-powershell/blob/node-shell/examples/2.longer-basic-usage.ts and don't quite get it to work. After the first invoke the internal state of the shell shows Failed and I can't figure out why. Any ideas? Other than that it looks like a bit of refactoring to unwrap the result text of the invoke returns as this is now an object but that is understandable.

**Comment by doublethinkio** [comment]
> @sopelt
> ![image](https://user-images.githubusercontent.com/11806915/79676572-1dc7f800-81f0-11ea-98c8-f457a4b46132.png)
> 
> Regarding the name thing, this version I implemented the NPS base classes with an abstract layer that would now allow me to apply a cover to any other shell I want quite easily and fast. The name of the package will not change but new packages (like node-bash etc ..) will be added very soon. All of them will be here in this repo (and I plan to use [lerna](https://github.com/lerna/lerna) to manage all the new packages). it will be fun :)

Wow, chain syntax looks pretty good

**Comment by vsamarcus** [comment]
Hi, do you have any delivery forecast for this fix?

**Comment by sopelt** [comment]
Thanks @rannn505 for your work! I am looking forward to giving 5.0.1 a spin ;)
