### ISSUE TITLE
Keep existing powershell session after a command?

### ISSUE THREAD

**Issue by DeveloperTommy** [rannn505/node-powershell#9]
Hi, I wasn't sure if this was possible but I was wondering if we could keep the same powershell session open?

For example:

Command #1: 
$a = Get-Command

Command #2:
$a[0] >> test.txt

Let's say I wanted to execute Command #1 then execute Command #2 at a later time programatically. Is this possible?

**Comment by rannn505** [comment]
Hey @DeveloperTommy  
Please check out the new features entered in the last commit,
The module now keeps the same powershell runspace for each shell object until dispose() is called.
