### ISSUE TITLE
Toggle logging off for specific instances

### ISSUE THREAD

**Issue by mikebutak** [rannn505/node-powershell#90]
Hello,

I see that [this thread](https://github.com/rannn505/node-powershell/issues/30) provides a solution for turning off all console logging in Node for node-powershell.  

Rather than turn it off globally, I'd like to turn it off for one specific method (because the parameters being passed to PowerShell contain sensitive information).  I tried the following, but it didn't work:  

const shell = require('node-powershell');

```
let ps = new shell({
  executionPolicy: 'Bypass',
  noProfile: true,
  debugMsg: true
});

let doSomethingSensitive = (cb, params, res) => {
  ps.debugMsg = false; // this suppresses logging for this request 
  ps.addCommand(`Import-Module 'C:\\...psm1' -Force`);
  ps.addCommand(`Invoke-....`)
  ps.invoke()
  .then( output => {
    console.log('result from ....psm1: ', output);
      if(output == 1 || output == 2) {
        cb( '1', res);
      } else { 
        cb( output, res);
      }
  })
}
```

Any guesses why `ps.debugMsg = false;`  doesn't suppress logging?  

Any suggestions?  Thanks!

**Comment by mikebutak** [comment]
Ah, I see my error.  debugMsg is not a property of the ps object but rather a property of the object passed to the constructor used to create the ps object.  

Solved it this way:

const shell = require('node-powershell');

```
let ps = new shell({
  executionPolicy: 'Bypass',
  noProfile: true,
  debugMsg: true
});

let ps_no_logs = new shell ({
  executionPolicy: 'Bypass',
  noProfile: true,
  debugMsg: false
})
```

Now I simply use the ps_no_logs object within functions for which I want logging disabled.

**Comment by rannn505** [comment]
@mikebutak ,
I will try to implement a more sophisticated logging msgs on next big release
