### ISSUE TITLE
.addParameter Does Not Pass JSON object

### ISSUE THREAD

**Issue by 1LadyInDC** [rannn505/node-powershell#91]
I am passing a JSON object from my nodeJS my powershell script.  I am successful using the conventional ps.addCommand(<pathToPSScript>, <scriptParameters>); but when I use the ps.addCommand(<pathToPSScript>).then(() => ps.addParameter({<paramName>: <paramValue>}) it doesn't work.  

--------------------
utilsPS.js
----------------
const Shell = require('node-powershell');

exports.execPSScript = async (counter, command, scriptType, inputJson) => {
  const ps = new Shell({ executionPolicy: 'Bypass', verbose: true });
  const commandPath = '.\Get-MachineInfo.ps1';
  
  ps.addCommand(commandPath) 
     .then(() = ps.addParameter({name: 'JsonObj', value: inputJson});

  return ps.invoke();
}

-------------------------
Get-MachineInfo.ps1
-------------------------
param
(
  [string] $JsonObj
)

Write-Output $JsonObj
Write-Output "Num Args: " $args.length

-----------------------------------------------------------------
Am i missing something, because the same code works fine with the soon to be deprecated .addCommand(<scriptPath>, <scriptParameters>).

Thanks!

**Comment by BenjaminMichael** [comment]
I would caution you when wrapping node-powershell in a promise like that.  If you call it 1000 times sure that wont block the main thread but you just launched 1000 powershell instances.

But that's no big deal and wasn't your question.  Regarding your question, I always recommend template strings.


```javascript
const Shell = require('node-powershell');

exports.execPSScript = async (counter, command, scriptType, inputJson) => {
const ps = new Shell({ executionPolicy: 'Bypass', verbose: true });
ps.addCommand(`.\Get-MachineInfo.ps1 -JsonObj ${inputJSON}`)
ps.invoke().then(output => doStuff());
}
```


There are many different way to write this but if you read all the documentation it doesn't use one consistent pattern:
```javascript
let cmd1 = new PSCommand('Write-Host node-powershell').addParameter({foregroundcolor: 'red'}).addParameter({nonewline: null});
// and
ps.addCommand('./script.ps1');
ps.addCommand(`& "${require('path').resolve(__dirname, 'script.ps1')}"`);
// and
ps.addCommand('Write-Host node-powershell')
  .then(() => ps.addParameter({foregroundcolor: 'red'}))
  .then(() => ps.addParameter({nonewline: null})) //switch;
```

**Comment by rannn505** [comment]
`param
(
[string- USE OBJECT HERE OR CONVERT IT LATER TO JSON WITH Convert-ToJson COMD] $JsonObj
`)
