### ISSUE TITLE
could not handle error event which emit under constructor.

### ISSUE THREAD

**Issue by woodgear** [rannn505/node-powershell#92]
[Shell.js](https://github.com/rannn505/node-powershell/blob/HEAD/lib/Shell.js#L70)
```js
    if(!this.pid) {
      this.emit('error', new PS_PROC_ERROR());
    }
    proc.once('error', () => {
      this.emit('error', new PS_PROC_ERROR());
    });
```
how about throw a error

**Comment by rannn505** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve library errors](https://trello.com/c/EpkHavfd/61-improve-library-errors)
