### ISSUE TITLE
Callback/EOI never returns

### ISSUE THREAD

**Issue by cawoodm** [rannn505/node-powershell#96]
I have a similar problem to #94 where invoke() does not return. The problem is intermittant. In my application I have 4 instances of a Vue component which each instantiate their own `Shell` and call `Get-Service`. As you can see below, 3 of the 4 processes return whilst the 4th (PID 15456) does not. Repeat and only 2 return. About one in 10 times all 4 return.

Here's the code: https://github.com/cawoodm/powershell-servicemanager

![image](https://user-images.githubusercontent.com/498834/64476204-7203f780-d18c-11e9-9dee-d10383cd5479.png)

Could it be that the EOI detection is shaky? How does it work exactly?

**Comment by cawoodm** [comment]
I think I see the problem - you create a random string called `EOI` which looks like this `EOI_llKGpOg8x` and then you write it out using powershell after all other commands `[Console]::Out.Write("${EOI}")`.

The problem is that this line is not always streamed on it's own but sometimes together with the user's commands so `_write` get's something like this:

```
[{"Name":"Fax","Status":1,"DisplayName":"Fax","StartType":3,"CanStop":false},{"Name":"SysMain","Status":4,"DisplayName":"SysMain","StartType":2,"CanStop":true},{"Name":"WSearch","Status":4,"DisplayName":"Windows Search","StartType":2,"CanStop":true}]
EOI_llKGpOg8x
```

But it expects this separately like this:
```
[{"Name":"Fax","Status":1,"DisplayName":"Fax","StartType":3,"CanStop":false},{"Name":"SysMain","Status":4,"DisplayName":"SysMain","StartType":2,"CanStop":true},{"Name":"WSearch","Status":4,"DisplayName":"Windows Search","StartType":2,"CanStop":true}]
```
```
EOI_llKGpOg8x
```

Whether the output is streamed together or not is up to `child_process` and out side our control.

So this line in `utils.js` fails:
```javascript
if(chunk.compare(this.EOI) === 0) {
   cb();
   return this.emit('EOI');
}
```

It's doing a direct, absolute compare where it should be looking for the `EOI` string on a single line.

**Comment by cawoodm** [comment]
OK, I think we have a fix:

```json
_write(chunk, encoding, cb) {
// HERE
    if(chunk.indexOf(this.EOI) >= 0) {
      this.chunksArray.push(chunk);
      cb();
      return this.emit('EOI');
    }
    this.chunksArray.push(chunk);
    return cb();
  }
  isEmpty() {
    return this.chunksArray.length === 0;
  }
  getContents() {
    return Buffer.concat(this.chunksArray);
  }
  getContentsAsString(encoding = 'utf8') {
// AND HERE
    return Buffer.concat(this.chunksArray).toString(encoding).replace(/\0/g, '').replace(this.EOI,'');
  }
```

**Comment by codaamok** [comment]
@cawoodm I'm not sure if that is a fix, e.g. something trivial like printing `$host` (in PowerShell) results in same issue with the never returning. Also, with your changes in https://github.com/cawoodm/node-powershell/commit/863ef27896d1893bf4ea844deaff747c42891e86 a lot of the output is truncated (still using $host as an example).

**Comment by cawoodm** [comment]
It works for my application, feel free to improve on it.

**Comment by rannn505** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix invoke() promise never resolves bug](https://trello.com/c/luU5Pzb4/59-fix-invoke-promise-never-resolves-bug)
