### ISSUE TITLE
Question: Error on save?

### ISSUE THREAD

**Issue by JaeEmAre67** [rannn505/node-powershell#99]
Following the instructions to npm install -S node-powershell which ran fine, no issues, when I attempt to require (or even import) this and build all I get is a long error that starts:

 Error - [webpack] 'dist':
./node_modules/node-powershell/lib/Shell.js
Module not found: Error: Can't resolve 'child_process' in 'C:\users\mypath\git\my-redux\node_modules\node-powershell\lib'
resolve 'child_process' in 'C:\users\mypath\git\my-redux\node_modules\node-powershell\lib'
  Parsed request is a module

Am I missing a dependency?

**Comment by rannn505** [comment]
Hey @JaeEmAre67,
Why are you trying to build NPS? Do you have a requirement to support node lower then 6.0?

**Comment by rannn505** [comment]
Closed due to lack of response
